// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/list-articles.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/articles.ts
var SITE_URL = "https://https-advocaciak-niagarcia-com-br.lovable.app";
var articles = [
  { slug: "guia-completo-divorcio", title: "Div\xF3rcio em 2026: tipos, etapas, custos e como fazer com seguran\xE7a", desc: "Guia completo: modalidades, documentos, prazos e como fazer com seguran\xE7a." },
  { slug: "divorcio-online", title: "Div\xF3rcio online", desc: "Como se separar com seguran\xE7a, privacidade e sem sair de casa." },
  { slug: "divorcio-unilateral", title: "Div\xF3rcio sem assinatura do c\xF4njuge", desc: "STJ: \xE9 poss\xEDvel pedir o div\xF3rcio mesmo sem o consentimento do outro." },
  { slug: "quanto-custa-divorcio", title: "Quanto custa um div\xF3rcio?", desc: "Entenda os custos antes de tomar qualquer decis\xE3o." },
  { slug: "guarda-dos-filhos", title: "Como funciona a guarda dos filhos", desc: "Tipos de guarda, direitos dos pais e quando pedir mudan\xE7a na Justi\xE7a." },
  { slug: "pensao-retroativa", title: "Pens\xE3o aliment\xEDcia retroativa", desc: "Quando \xE9 poss\xEDvel cobrar valores atrasados e como calcular." },
  { slug: "alimentos-compensatorios", title: "Alimentos compensat\xF3rios", desc: "Decis\xE3o do TJGO reconhece direito ao reequil\xEDbrio econ\xF4mico no div\xF3rcio." },
  { slug: "pensao-filho-autismo", title: "Pens\xE3o para filho com autismo", desc: "Direitos, necessidades reais e a possibilidade de pens\xE3o vital\xEDcia." },
  { slug: "emancipacao", title: "Emancipa\xE7\xE3o", desc: "O que \xE9, tipos e como funciona no Direito Brasileiro." },
  { slug: "guarda-compartilhada", title: "Guarda Compartilhada", desc: "Direitos, deveres e como funciona na pr\xE1tica." },
  { slug: "comunhao-parcial-bens", title: "Comunh\xE3o Parcial de Bens", desc: "O regime patrimonial mais comum no Brasil." },
  { slug: "pensao-socioafetiva", title: "Pens\xE3o Socioafetiva", desc: "Direitos dos filhos afetivos e multiparentalidade." },
  { slug: "direitos-genitor", title: "Direitos do Genitor", desc: "O que a lei garante aos pais ap\xF3s a separa\xE7\xE3o." },
  { slug: "danos-morais", title: "Danos Morais no Direito de Fam\xEDlia", desc: "Quando cabe indeniza\xE7\xE3o em quest\xF5es familiares." },
  { slug: "uniao-estavel", title: "Uni\xE3o Est\xE1vel", desc: "Direitos, deveres e como formalizar." },
  { slug: "concubinato", title: "Concubinato", desc: "Diferen\xE7as para uni\xE3o est\xE1vel e direitos." }
];
var contactInfo = {
  name: "K\xEAnia Garcia Advocacia",
  areas: ["Direito de Fam\xEDlia", "Sucess\xF5es", "Div\xF3rcio", "Guarda", "Pens\xE3o aliment\xEDcia"],
  service: "Atendimento presencial ou online para todo Brasil ou exterior",
  instagram: "@drakeniagarciaadv",
  whatsapp: "+55 64 9 9988-1043",
  website: SITE_URL
};

// src/lib/mcp/tools/list-articles.ts
var list_articles_default = defineTool({
  name: "list_articles",
  title: "List articles",
  description: "List all published legal articles from K\xEAnia Garcia Advocacia (Brazilian family and succession law). Returns titles, slugs, descriptions and URLs.",
  inputSchema: {
    search: z.string().optional().describe("Optional case-insensitive substring to filter articles by title or description.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ search }) => {
    const q = (search ?? "").trim().toLowerCase();
    const items = articles.filter((a) => !q || a.title.toLowerCase().includes(q) || a.desc.toLowerCase().includes(q)).map((a) => ({ ...a, url: `${SITE_URL}/artigos/${a.slug}` }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { articles: items, count: items.length }
    };
  }
});

// src/lib/mcp/tools/get-article.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_article_default = defineTool2({
  name: "get_article",
  title: "Get article",
  description: "Return metadata and the public URL for a specific article by its slug. Fetch the URL to read the full content.",
  inputSchema: {
    slug: z2.string().min(1).describe("Article slug, e.g. 'divorcio-online'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const article = articles.find((a) => a.slug === slug);
    if (!article) {
      return {
        content: [{ type: "text", text: `Article not found: ${slug}` }],
        isError: true
      };
    }
    const result = { ...article, url: `${SITE_URL}/artigos/${slug}` };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
var get_contact_info_default = defineTool3({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Return contact information for K\xEAnia Garcia Advocacia: practice areas, WhatsApp, Instagram, and website.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(contactInfo, null, 2) }],
    structuredContent: contactInfo
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "kenia-garcia-advocacia-mcp",
  title: "K\xEAnia Garcia Advocacia",
  version: "0.1.0",
  instructions: "Public MCP server for K\xEAnia Garcia Advocacia. Use `list_articles` to browse published legal articles on Brazilian family and succession law, `get_article` to get the URL for a specific article by slug (fetch the URL to read the content), and `get_contact_info` for practice areas and contact channels.",
  tools: [list_articles_default, get_article_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
